output_dir: "results"
seed: 10
task: "ANONYMIZED"
dryrun: False
save_prompts: True
timeout: 0.0
task_config: 
    profile_path: "data/base_inferences/synthetic/test_profile.jsonl"
    outpath: "anonymized_results/test_real_profile_gpt4o"  # Change this
    anonymizer: 
      anon_type: "llm"
      target_mode: "single"
      max_workers: 1
    anon_model:
      name: "gpt-4o"
      provider: "openai"
      args: {
        temperature: 0.1
      }
    inference_model:
      name: "gpt-4o"
      provider: "openai"
      args: {
        temperature: 0.1
      }
    utility_model:
      name: "gpt-4o"
      provider: "openai"
      args: {
        temperature: 0.1
      }
    profile_filter:
      hardness: 1
      certainty: 1
      num_tokens: 1000
    max_num_iterations: 2
    use_ner: False
    offset: 0
    num_profiles: 2
gen_model:
  name: "gpt-3.5-turbo"
  provider: "openai"
  args: {
    temperature: 0.1
  }